name: 1.0$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    gulp default --version 1.0.0
  displayName: 'npm install and run gulp'
