pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm audit
    npm ci
    npx -q git2semver --formatter majorminorpatch-pipelines-variables-and-label
    npm version $GIT2SEMVER_MAJORMINORPATCH --no-git-tag-version
    node_modules/.bin/vsce package